import { useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import confetti from 'canvas-confetti'
import { ArrowLeft, ArrowRight, Check, Download, Heart, RotateCcw, Sparkles, Shuffle, Volume2, VolumeX } from 'lucide-react'
import { dateOptions, sarcasticComments } from './data/dateOptions'
import { siteConfig } from './config/siteConfig'
import './App.css'
import './planner.css'

const confirmationStages = [
  ['Are you sure? 🥺', 'Maybe you clicked the wrong button…', "No, I'm sure 😭"],
  ['Wait… REALLY? 😭', "You're actually saying no?", 'Still No 😭'],
  ["You don't wanna love me like that? 💔", 'Think about this carefully…', "I'm still saying NO 😭"],
  ['Final answer? 🥹', "You really don't want a date with me?", "I'm sure I don't want to 😭"],
]
const screenMotion = { initial: { opacity: 0, x: 18 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -18 } }

function FloatingAtmosphere({ dark = false }) {
  const hearts = ['♡', '✦', '♥', '·', '✧', '♡', '✦', '·']
  return <div className={`atmosphere ${dark ? 'atmosphere-dark' : ''}`} aria-hidden="true"><div className="glow glow-one" /><div className="glow glow-two" />{hearts.map((heart, index) => <span className={`float float-${index + 1}`} key={`${heart}-${index}`}>{heart}</span>)}</div>
}
function Button({ children, variant = 'primary', onClick, icon: Icon, type = 'button', ...props }) { return <motion.button whileHover={{ y: -3 }} whileTap={{ scale: .97 }} className={`button button-${variant}`} type={type} onClick={onClick} {...props}>{Icon && <Icon size={17} strokeWidth={2.2} />}{children}</motion.button> }
function Screen({ children, dark = false }) { return <main className={`screen ${dark ? 'screen-dark' : ''}`}><FloatingAtmosphere dark={dark} /><div className="screen-inner">{children}</div></main> }
function Welcome({ onOpen }) { return <Screen><motion.div className="welcome-layout" {...screenMotion}><div className="eyebrow"><span className="eyebrow-dot" /> A small note from my heart</div><div className="welcome-copy"><p className="script">For the person who makes ordinary days feel like a story</p><h1>{siteConfig.welcomeText} <span className="heart-mark">♥</span></h1><p className="lede">I made something special for you.<br />Take a breath, then come a little closer.</p></div><Button onClick={onOpen} icon={ArrowRight}>Open My Heart</Button><p className="tiny-note">made with too much thought & a little bit of courage</p></motion.div></Screen> }
function Proposal({ onYes, onNo, onBack }) { return <Screen><motion.div className="story-layout" {...screenMotion}><div className="story-meta"><span>01 / 05</span><span className="line" /><span>the question</span></div><div className="question-ornament"><Heart size={22} fill="currentColor" /></div><h2>{siteConfig.proposalTitle}</h2><p className="lede">{siteConfig.proposalSubtitle}</p><div className="button-row"><Button onClick={onYes} icon={Heart}>Yes, absolutely</Button><Button onClick={onNo} variant="ghost">No 🙃</Button></div><button className="back-link" onClick={onBack}><ArrowLeft size={14} /> back to the beginning</button></motion.div></Screen> }
function Confirmation({ attempt, onYes, onNo }) { const stage = confirmationStages[attempt]; return <Screen><motion.div className="story-layout confirmation" {...screenMotion} key={attempt}><div className="story-meta"><span>one more thought</span><span className="line" /><span>0{attempt + 2} / 05</span></div><div className="question-emoji">{['🥺', '😭', '💔', '🥹'][attempt]}</div><h2>{stage[0]}</h2><p className="lede">{stage[1]}</p><div className="button-row"><Button onClick={onYes} icon={Heart}>{attempt === 2 ? 'Okay fine, YES' : "Yes, let's go"}</Button><Button onClick={onNo} variant="ghost">{stage[2]}</Button></div><p className="tiny-note">You can always say no. I mean it. ♡</p></motion.div></Screen> }
function NoThanks({ onBack }) { return <Screen><motion.div className="story-layout" {...screenMotion}><div className="question-emoji">♡</div><h2>Okay… I'll respect your answer.</h2><p className="lede">No pressure. Your choice matters.</p><Button onClick={onBack} icon={ArrowLeft} variant="ghost">Go back</Button></motion.div></Screen> }
function Celebration({ onPlan }) { useEffect(() => { confetti({ particleCount: 150, spread: 90, origin: { y: .62 }, colors: ['#ff4f70', '#ffb36b', '#fff5e7', '#a98bff'] }) }, []); return <Screen><motion.div className="story-layout celebration" {...screenMotion}><div className="celebration-badge"><Sparkles size={17} /> it's official</div><div className="question-emoji">💌</div><h2>YAYYYYY!!! <span className="heart-mark">♥</span></h2><p className="lede">You said yes.<br /><strong>Okay… now let's plan our date.</strong></p><Button onClick={onPlan} icon={ArrowRight}>Plan our date</Button></motion.div></Screen> }

function Progress({ plannerStep, total, category, onBack, onSurprise }) {
  const labels = ['❤️ Date', ...category.map((item) => `${item.emoji} ${item.title}`), '✨ Final Plan']
  return <div className="planner-head"><div className="planner-progress"><span className="step-count">Step {plannerStep + 1} of {total + 1}</span><div className="step-dots">{labels.map((label, index) => <span className={index <= plannerStep ? 'active' : ''} key={label}>{label}</span>)}</div></div><div className="planner-actions"><button className="back-link" onClick={onBack}><ArrowLeft size={14} /> Back</button><button className="surprise-button" onClick={onSurprise}><Shuffle size={14} /> Surprise me</button></div></div>
}
function DateTypeSelection({ onSelect, onSurprise }) { return <Screen><motion.div className="selection-layout" {...screenMotion}><div className="story-meta"><span>02 / 05</span><span className="line" /><span>choose a feeling</span></div><h2>Okay, let's build our perfect date. <span className="heart-mark">♥</span></h2><p className="lede">This is where your questionable decision-making begins. 😌</p><div className="date-grid">{dateOptions.map((option, index) => <motion.button className={`date-card card-${option.accent}`} key={option.id} onClick={() => onSelect(option)} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .1 }} whileHover={{ y: -8 }} whileTap={{ scale: .98 }}><div className="card-top"><span className="card-emoji">{option.emoji}</span><span className="card-arrow"><ArrowRight size={17} /></span></div><span className="card-kicker">{option.short}</span><strong>{option.title}</strong><span className="card-description">{option.description}</span><span className="select-label">choose this <ArrowRight size={14} /></span></motion.button>)}</div><button className="surprise-button planner-surprise" onClick={onSurprise}><Shuffle size={15} /> Surprise me. I choose chaos. 🎲</button></motion.div></Screen> }
function CategorySelection({ option, plannerStep, onSelect, onBack, onSurprise }) { return <Screen><motion.div className="selection-layout deep-layout" {...screenMotion}><Progress plannerStep={plannerStep} total={option.categories.length} category={option.categories} onBack={onBack} onSurprise={onSurprise} /><div className="choice-heading"><span className={`large-emoji card-${option.accent}`}>{option.emoji}</span><div><p className="card-kicker">{option.title}</p><h2>Okay babe, we're planning an entire relationship now. 😭❤️</h2></div></div><p className="lede">Three categories. Zero chance of making this decision quickly.</p><div className="category-grid">{option.categories.map((category, index) => <motion.button className={`category-card ${index === plannerStep ? 'category-current' : ''}`} key={category.id} onClick={() => onSelect(index)} whileHover={{ y: -5 }} whileTap={{ scale: .98 }}><span className="category-number">0{index + 1}</span><span className="category-emoji">{category.emoji}</span><strong>{category.title}</strong><small>{index === plannerStep ? 'choose this next' : index < plannerStep ? 'completed · change it' : 'coming up'}</small>{index < plannerStep && <Check className="category-check" size={16} />}</motion.button>)}</div></motion.div></Screen> }
function OptionSelection({ option, category, plannerStep, onSelect, onBack, onSurprise }) { return <Screen><motion.div className="selection-layout deep-layout" {...screenMotion}><Progress plannerStep={plannerStep} total={option.categories.length} category={option.categories} onBack={onBack} onSurprise={onSurprise} /><div className="choice-heading"><span className="large-emoji">{category.emoji}</span><div><p className="card-kicker">{category.title}</p><h2>{category.prompt}</h2></div></div><p className="lede">Choose carefully. Apparently this decision determines our entire personality now. 😭</p><div className="option-grid">{category.options.map((choice) => <motion.button className="deep-option" key={choice.id} onClick={() => onSelect(choice)} whileHover={{ y: -5 }} whileTap={{ scale: .98 }}><span className="option-icon">{choice.emoji}</span><strong>{choice.title}</strong><small>{choice.description}</small><span className="option-cta">choose <ArrowRight size={14} /></span></motion.button>)}</div></motion.div></Screen> }
function SubOptionSelection({ option, category, choice, plannerStep, onSelect, onBack, onSurprise }) { return <Screen><motion.div className="selection-layout deep-layout" {...screenMotion}><Progress plannerStep={plannerStep} total={option.categories.length} category={option.categories} onBack={onBack} onSurprise={onSurprise} /><div className="choice-heading"><span className="large-emoji">{choice.emoji}</span><div><p className="card-kicker">{category.title} · {choice.title}</p><h2>Now pick the exact flavor of chaos.</h2></div></div><p className="lede">{choice.description}</p><div className="suboption-list">{choice.subOptions.map((subOption, index) => <motion.button className="suboption" key={subOption} onClick={() => onSelect(subOption)} initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }} whileHover={{ x: 6 }}><span className="sub-number">0{index + 1}</span><strong>{subOption}</strong><ArrowRight size={18} /></motion.button>)}</div></motion.div></Screen> }
function RomanceMeter({ selections }) { const level = selections.some((item) => /romantic|romance|candle|sunset|couple/i.test(item)) ? 'Dangerously Romantic 😭❤️' : selections.some((item) => /adventure|horror|action|drive/i.test(item)) ? 'Main Character Couple 🎬❤️' : selections.some((item) => /fancy|rooftop|spa/i.test(item)) ? 'Okay, Calm Down Romeo. 😂' : 'Very Cute ❤️'; return <div className="romance-meter"><div className="meter-title"><span>Total Romance Level</span><strong>{level}</strong></div><div className="meter-track"><motion.span initial={{ width: 0 }} animate={{ width: `${Math.min(94, 50 + selections.length * 12)}%` }} /></div></div> }
function Summary({ option, selections, message, setMessage, onCreate, onBack, onSurprise }) { const detailItems = option.categories.map((category) => ({ category, choice: selections.find((item) => item.categoryId === category.id) })); return <Screen><motion.div className="summary-layout deep-summary" {...screenMotion}><div className="planner-actions summary-actions"><button className="back-link" onClick={onBack}><ArrowLeft size={14} /> Back</button><button className="surprise-button" onClick={onSurprise}><Shuffle size={14} /> Surprise me</button></div><p className="card-kicker">okay… we actually planned this. 😭</p><h2>Our Date <span className="heart-mark">♥</span></h2><div className={`summary-card card-${option.accent}`}><div className="summary-icon">{option.emoji}</div><div><span>Date type</span><strong>{option.title}</strong></div>{detailItems.map(({ category, choice }) => <div className="summary-detail" key={category.id}><span>{category.emoji} {category.title}</span><strong>{choice?.choice} <small>{choice?.subOption}</small></strong></div>)}<p>Somehow this became a full production. But honestly? It's cute.</p></div><RomanceMeter selections={selections.flatMap((item) => [item.choice, item.subOption])} /><label className="message-label" htmlFor="message">Anything else you want to add?</label><textarea id="message" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="A tiny note for our future selves…" rows="3" /><Button onClick={onCreate} icon={Sparkles}>Create our date plan</Button></motion.div></Screen> }
function FinalScreen({ option, selections, message, onSave, onStartOver }) { return <Screen dark><motion.div className="final-layout deep-final" {...screenMotion}><div className="final-topline"><span>our little love story</span><Heart size={15} fill="currentColor" /></div><p className="script">mark your calendar</p><h2>IT'S A DATE <span className="heart-mark">♥</span></h2><p className="final-sarcasm">Somehow, we just spent all this time planning one date.<br /><strong>But honestly… I'm glad it's with you. ❤️</strong><br />Now don't cancel on me. 😭</p><div className="final-plan"><div><span>Date type</span><strong>{option.emoji} {option.title}</strong></div>{selections.map((item) => <div key={item.categoryId}><span>{item.categoryEmoji} {item.categoryTitle}</span><strong>{item.choice}<small>{item.subOption}</small></strong></div>)}{message && <p>“{message}”</p>}</div><div className="button-row"><Button onClick={onSave} icon={Download}>Save our date</Button><Button onClick={onStartOver} variant="light" icon={RotateCcw}>Start over</Button></div></motion.div></Screen> }
function MusicToggle({ enabled, onToggle }) { return <button className="music-toggle" onClick={onToggle} aria-label={enabled ? 'Turn music off' : 'Turn music on'}>{enabled ? <Volume2 size={16} /> : <VolumeX size={16} />}<span>{enabled ? 'music on' : 'music off'}</span></button> }

function App() {
  const [screen, setScreen] = useState('welcome'); const [attempt, setAttempt] = useState(0); const [selectedOption, setSelectedOption] = useState(null); const [plannerStep, setPlannerStep] = useState(0); const [activeCategory, setActiveCategory] = useState(null); const [activeChoice, setActiveChoice] = useState(null); const [selections, setSelections] = useState([]); const [message, setMessage] = useState(''); const [musicEnabled, setMusicEnabled] = useState(false); const [commentIndex, setCommentIndex] = useState(0); const audioRef = useRef(null)
  const progress = useMemo(() => screen === 'dateType' ? 3 : screen === 'final' ? 6 : screen === 'summary' ? 5 : screen === 'planner' ? 4 : screen === 'subOption' ? 4 : 0, [screen])
  const selectDate = (option) => { setSelectedOption(option); setPlannerStep(0); setActiveCategory(null); setSelections([]); setScreen('planner') }
  const showComment = () => setCommentIndex((index) => (index + 1) % sarcasticComments.length)
  const selectCategory = (index) => { setPlannerStep(index); setActiveCategory(selectedOption.categories[index]); setScreen('option') }
  const selectChoice = (choice) => { setActiveChoice(choice); setScreen('subOption') }
  const selectSubOption = (subOption) => { const next = [...selections.filter((item) => item.categoryId !== activeCategory.id), { categoryId: activeCategory.id, categoryTitle: activeCategory.title, categoryEmoji: activeCategory.emoji, choice: activeChoice.title, subOption }]; setSelections(next); showComment(); if (plannerStep < selectedOption.categories.length - 1) { setPlannerStep((step) => step + 1); setActiveCategory(null); setActiveChoice(null); setScreen('planner') } else setScreen('summary') }
  const surpriseMe = () => { const next = selectedOption ? selectedOption.categories.map((category) => { const choice = category.options[Math.floor(Math.random() * category.options.length)]; return { categoryId: category.id, categoryTitle: category.title, categoryEmoji: category.emoji, choice: choice.title, subOption: choice.subOptions[Math.floor(Math.random() * choice.subOptions.length)] } }) : dateOptions[Math.floor(Math.random() * dateOptions.length)]; if (!selectedOption) { selectDate(next); return } setSelections(next); setScreen('summary'); showComment() }
  const savePlan = () => { const content = `OUR DATE ❤️\n\n${siteConfig.herName} + ${siteConfig.myName}\n${selectedOption.title}\n${selections.map((item) => `${item.categoryTitle}: ${item.choice} — ${item.subOption}`).join('\n')}\n${message ? `\nA note: ${message}` : ''}\n\nMade with love.`; const blob = new Blob([content], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'our-date-plan.txt'; link.click(); URL.revokeObjectURL(url) }
  const toggleMusic = () => { const next = !musicEnabled; setMusicEnabled(next); if (next) { if (!audioRef.current) audioRef.current = new Audio('/music.mp3'); audioRef.current.loop = true; audioRef.current.play().catch(() => setMusicEnabled(false)) } else audioRef.current?.pause() }
  const reset = () => { setScreen('welcome'); setAttempt(0); setSelectedOption(null); setPlannerStep(0); setActiveCategory(null); setActiveChoice(null); setSelections([]); setMessage('') }
  const goBack = () => { if (screen === 'planner') { setScreen('dateType'); return } if (screen === 'option') { setScreen('planner'); return } if (screen === 'subOption') { setScreen('option'); return } if (screen === 'summary') { setScreen('planner'); setPlannerStep(selectedOption.categories.length - 1); return } }

  return <div className="app-shell"><div className="progress-bar"><span style={{ width: `${Math.max(7, progress / 6 * 100)}%` }} /></div><MusicToggle enabled={musicEnabled} onToggle={toggleMusic} /><AnimatePresence mode="wait">
    {screen === 'welcome' && <Welcome key="welcome" onOpen={() => setScreen('proposal')} />}
    {screen === 'proposal' && <Proposal key="proposal" onYes={() => setScreen('celebration')} onNo={() => { setAttempt(0); setScreen('confirmation') }} onBack={() => setScreen('welcome')} />}
    {screen === 'confirmation' && <Confirmation key={`confirmation-${attempt}`} attempt={attempt} onYes={() => setScreen('celebration')} onNo={() => attempt < 3 ? (setAttempt((value) => value + 1), setScreen('confirmation')) : setScreen('noThanks')} />}
    {screen === 'noThanks' && <NoThanks key="noThanks" onBack={() => setScreen('proposal')} />}
    {screen === 'celebration' && <Celebration key="celebration" onPlan={() => setScreen('dateType')} />}
    {screen === 'dateType' && <DateTypeSelection key="dateType" onSelect={selectDate} onSurprise={surpriseMe} />}
    {screen === 'planner' && <CategorySelection key={`planner-${plannerStep}`} option={selectedOption} plannerStep={plannerStep} onSelect={selectCategory} onBack={goBack} onSurprise={surpriseMe} />}
    {screen === 'option' && <OptionSelection key={`option-${plannerStep}`} option={selectedOption} category={activeCategory} plannerStep={plannerStep} onSelect={selectChoice} onBack={goBack} onSurprise={surpriseMe} />}
    {screen === 'subOption' && <SubOptionSelection key={`sub-${plannerStep}`} option={selectedOption} category={activeCategory} choice={activeChoice} plannerStep={plannerStep} onSelect={selectSubOption} onBack={goBack} onSurprise={surpriseMe} />}
    {screen === 'summary' && <Summary key="summary" option={selectedOption} selections={selections} message={message} setMessage={setMessage} onCreate={() => setScreen('final')} onBack={goBack} onSurprise={surpriseMe} />}
    {screen === 'final' && <FinalScreen key="final" option={selectedOption} selections={selections} message={message} onSave={savePlan} onStartOver={reset} />}
  </AnimatePresence><div className="toast-comment" key={commentIndex}>{screen !== 'welcome' && screen !== 'proposal' && sarcasticComments[commentIndex]}</div><footer><span>Our Little Love Story</span><span>made for {siteConfig.herName}</span></footer></div>
}
export default App
